name: CI + CD (Post-Merge Only)

on:
  push:
    branches: [main]  # Only trigger after merge into main

permissions:
  contents: write  # Required for GitHub Pages deployment

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v4

      - name: ✅ JavaScript Syntax Check
        run: |
          js_files=$(find . -name "*.js" -not -path "./node_modules/*" | head -20)
          if [ -z "$js_files" ]; then
            echo "No JavaScript files found - skipping JS validation"
          else
            echo "Found JavaScript files - running syntax check..."
            for file in $js_files; do
              echo "Checking JS: $file"
              node -c "$file" || exit 1
            done
            echo "✅ All JavaScript files passed syntax check!"
          fi

      - name: ✅ CSS Validation
        run: |
          css_files=$(find . -name "*.css" -not -path "./node_modules/*" | head -10)
          if [ -z "$css_files" ]; then
            echo "No CSS files found - skipping CSS validation"
          else
            echo "Found CSS files - running validation..."
            for file in $css_files; do
              echo "Checking CSS: $file"
              # Simple CSS syntax check - look for basic structure
              if ! grep -q "{" "$file" || ! grep -q "}" "$file"; then
                echo "Warning: $file might not be valid CSS"
              fi
            done
            echo "✅ CSS files checked!"
          fi

      - name: ✅ HTML Validation
        run: |
          html_files=$(find . -name "*.html" -not -path "./node_modules/*" | head -10)
          if [ -z "$html_files" ]; then
            echo "No HTML files found - skipping HTML validation"
          else
            echo "Found HTML files - running validation..."
            for file in $html_files; do
              echo "Checking HTML: $file"
              # Basic HTML check - ensure it has proper structure
              if ! grep -q "<html" "$file" && ! grep -q "<!DOCTYPE" "$file"; then
                echo "Warning: $file might not be valid HTML"
              fi
            done
            echo "✅ HTML files checked!"
          fi

      - name: ✅ Markdown Validation
        run: |
          echo "Validating Markdown files..."
          for file in $(find . -name "*.md"); do
            echo "Checking: $file"
            if [ ! -s "$file" ]; then
              echo "Error: $file is empty"
              exit 1
            fi
          done
          echo "✅ All Markdown files are valid!"

      - name: ✅ Check Required Files
        run: |
          echo "Checking for required repository files..."
          required_files=("README.md" "LICENSE" "CONTRIBUTING.md")
          for file in "${required_files[@]}"; do
            if [ ! -f "$file" ]; then
              echo "Error: Missing required file: $file"
              exit 1
            else
              echo "✓ Found: $file"
            fi
          done

  deploy:
    needs: validate
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v4

      - name: 🚀 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Deploy all repository content including README.md
